### ISSUE TITLE
Is there a way to have multiple formats without duplicating record

### ISSUE THREAD

**Issue by przbadu** [andreapavoni/panoramic#21]
I want something like this for example:

``` ruby
TemplateStorage.create(body: '###mailer with text and html format', path: 'user_mailer/testing', handler: 'liqmd', formats: ['html', 'text'])
```

here `handler: 'liqmd'` is the `liquid_markdown` gem which I am working on. That's the reason I don't have to duplicate records for `format: 'html'` and `format: 'text'`  with exactly same `body`. So it would be great if I can put both `html` and `text` together in `format` column.

It is working well if I duplicate record with `format: 'html' and format: 'text'`

``` ruby
TemplateStorage.create(body: '###mailer with text and html format', path: 'user_mailer/testing', handler: 'liqmd', format: 'html')
TemplateStorage.create(body: '###mailer with text and html format', path: 'user_mailer/testing', handler: 'liqmd', format: 'text')
```

Thanks

**Comment by andreapavoni** [comment]
Well, as far as I know, you can't. This gem works just like normal rails views, the only difference is it uses a db to store templates rather than filesystem. In a normal rails view, you should create two files anyway, so does panoramic gem ;-)

**Comment by przbadu** [comment]
@andreapavoni thanks for your reply 👍 

I have one more question:

Suppose I have mailer setup like this:

```ruby
class UserMailer < ApplicationMailer  
   prepend_view_path TemplateStorage.resolver

  def hello
    mail(to: 'someone@example.com') do |format|
      format.html
      format.text
    end
  end
end
```

And I have it's body in database:

`TemplateStorage.create(body: '###mailer with text and html format', path: 'user_mailer/hello', handler: 'liqmd', format: 'html')
`

Is it possible to get both `html` and `text` version with this approach?

**Comment by andreapavoni** [comment]
@przbadu mailer templates work just like normal Rails templates, so you can't have this for the same reasons. After all, normal mailer templates are single dedicated files anyway.

**Comment by przbadu** [comment]
@andreapavoni thanks
