### ISSUE TITLE
Scoping templates by theme in a CMS

### ISSUE THREAD

**Issue by vitobotta** [andreapavoni/panoramic#38]
Hi! I am working on a CMS that lets users create/manage templates. These templates should be scoped by theme though. What is the best way to achieve this with panoramic? I see that there is a related issue but it's very old and I think it no longer applies to current versions of the gem and Rails. Thanks in advance for any help!

**Comment by andreapavoni** [comment]
@vitobotta I suppose you found the answer in the README :-)

The point of panoramic is that you can store views on database by using the tools it offers to make it as transparent and easy to use as possible. Where or when to use them is up to you. In your case, you might create a model to store the views + the data you need for your desired namespacing logic.
