### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by t3k4y** [andreapavoni/panoramic#69]
Thank you for your work on this gem! 

I would kindly ask if it is still maintained since the PR-queue is long..

Best wishes!

**Comment by andreapavoni** [comment]
HU @t3k4y 

this repository is in a sort of survival mode, in which I put the minimal maintenance effort to keep it live.

the PRs are mostly dependabot updates and, here comes the point: I'd be glad to help and contribute more if I only ever get some PR from the devs/companies which are using this gem.

as you can see from the PRs history, this project got only a bunch of stars on github but not too much contributions or collaborations.

**Comment by t3k4y** [comment]
Hey Andrea,
thank you for your fast reply! And good to know, that its on survival mode (at least)!
If we can provide improvements we'll let you know.
